---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synophoto-sessions
  namespace: default
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: sc-nas
  resources:
    requests:
      storage: 1Gi
