---
apiVersion: v1
kind: Secret
metadata:
  name: synophoto-secret
  namespace: default
stringData:
  AUTH0_DOMAIN: "${SYNOPHOTO_AUTH0_DOMAIN}"
  AUTH0_CLIENT_ID: "${SYNOPHOTO_AUTH0_CLIENT_ID}"
  AUTH0_CLIENT_SECRET: "${SYNOPHOTO_AUTH0_CLIENT_SECRET}"
  ALLOWED_EMAILS: "${SYNOPHOTO_ALLOWED_EMAILS}"
  FLASK_SECRET_KEY: "${SYNOPHOTO_FLASK_SECRET_KEY}"
  NAS_USERNAME: "${SYNOPHOTO_NAS_USERNAME}"
  NAS_PASSWORD: "${SYNOPHOTO_NAS_PASSWORD}"
