---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./local-pvc.yaml
  - ./secret.yaml
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./helmrelease1.yaml
  - ./certificate.yaml
  - ./ingress.yaml
  - ./httproute.yaml
  - ./udp-gateway.yaml
  - ./udproute.yaml
