---
apiVersion: v1
kind: Secret
metadata:
  name: trello-notifier-secret
  namespace: default
stringData:
  TRELLO_API_KEY: "${TRELLO_API_KEY}"
  TRELLO_API_TOKEN: "${TRELLO_API_TOKEN}"
  TRELLO_BOARD_ID: "${TRELLO_BOARD_ID}"
  LINE_CHANNEL_ACCESS_TOKEN: "${LINE_CHANNEL_ACCESS_TOKEN}"
  LINE_NOTIFY_GROUP_ID: "${LINE_NOTIFY_GROUP_ID}"
